name: Build Netmotive EXE

on:
  push:                 # build on every push to main
    branches: [ main ]
  workflow_dispatch:    # allow manual “Run workflow” button

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣  Check out source
      - uses: actions/checkout@v4

      # 2️⃣  Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣  Install requirements & PyInstaller
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      # 4️⃣  Build EXE and bundle Qt platform plugin
      - name: Build with PyInstaller (Qt plugins bundled)
        shell: pwsh
        run: |
          # Locate the PySide6 plugins\platforms directory
          $pluginsDir = python -c "import sysconfig, pathlib, sys; p = pathlib.Path(sysconfig.get_paths()['platlib']) / 'PySide6' / 'plugins' / 'platforms'; print(p)"
          $pluginsDir = $pluginsDir.Trim()

          echo \"Qt platforms dir: $pluginsDir\"

          # Build one-file, windowed EXE, bundling the plugin directory
          pyinstaller --noconfirm --onefile --windowed `
            --add-data="$pluginsDir;platforms" `
            netmotive_ip_range_changer.py

      # 5️⃣  Upload artifact
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: Netmotive_IP_Range_Changer
          path: dist/netmotive_ip_range_changer.exe
